server:
  port: 9527


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route  #路由的id,没有规定规则但要求唯一,建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE     #这里的lb是loadbalance负载均衡
         # uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配的进行路由

        - id: payment_route2  #路由的id,没有规定规则但要求唯一,建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
            - After=2020-10-19T15:38:08.003+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy   #带有cookie访问
            #- Header=X-Request-Id, \d+ #请求头带有equest-Id属性并且值为整数的正则表达式




eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
